project/apps/altaVehiculo/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'altaVehiculo'

urlpatterns = [
    path("", TemplateView.as_view(template_name="altaVehiculo/index.html"), name="home"),
    path('nuevo_alta_vehiculo',views.AltaVehiculoCreate.as_view(), name='create'),
    path('list_alta_vehiculo/', views.AltaVehiculoList.as_view(), name='list'),
    path('detail_alta/<int:pk>', views.AltaVehiculoDetail.as_view(), name="detail_alta")
]

project/apps/home/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import home

app_name = "home"

urlpatterns = [
    path("", home, name="home"),

]

urlpatterns += staticfiles_urlpatterns()

project/config/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("vehiculo/", include("vehiculo.urls")),
    path("cliente/", include("cliente.urls")),
    path("altaVehiculo/", include("altaVehiculo.urls")),
    path("repuestos/", include("repuestos.urls")),
    
]

project/apps/home/models.py
from django.db import models

# Create your models here.

project/apps/home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "home/index.html")

project/apps/home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Registro Automotor</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}  " />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->

        {% include 'home/navbar.html' %}

        <!-- Page Content-->
        <div class="container px-4 px-lg-5">

            {% block BASE_CONTENIDO %}


            {% endblock BASE_CONTENIDO %}

        </div>
        <!-- Footer-->
        {% include 'home/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %} "></script>
    </body>
</html>

project/apps/home/templates/home/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ card }}</h2>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="{%url vinculo%}" >Ir</a></div>
    </div>
</div>

project/apps/home/templates/home/footer.html
<footer class="bg-dark fixed-bottom ">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Mi pagina web</p></div>
</footer>

project/apps/home/templates/home/index.html
{% extends 'Home/base.html' %}
{% load static %}

{% block BASE_CONTENIDO %}

    <div class="row align-items-center my-5">
        <h1 class="pb-lg-3 text-bg-light">
            {% block INDEX_TITULO %}
                Bienvenido!!!
            {% endblock INDEX_TITULO %}
        </h1>
    </div>

    {% block INDEX_CONTENIDO %}



        <!-- Content Row-->
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">crear vehiculo</h2>
                    </div>
                    <div class="card-footer"><a class="btn btn-primary btn-sm" href="{%url "altaVehiculo:create"%}" >Ir</a></div>
                </div>
            </div>
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">ver vehiculos</h2>
                    </div>
                    <div class="card-footer"><a class="btn btn-primary btn-sm" href="{%url "altaVehiculo:list"%}">Ir</a></div>
                </div>
            </div>
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">nose</h2>
                    </div>
                    <div class="card-footer"><a class="btn btn-primary btn-sm">Ir</a></div>
                </div>
            </div>
        </div>
    {% endblock INDEX_CONTENIDO %}

{% endblock BASE_CONTENIDO %}

project/apps/home/templates/home/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Registro de autos</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Sobre nosotros</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Contacto</a></li>
            </ul>
        </div>
    </div>
</nav>